### ISSUE TITLE
random crash while playing or loading a world

### ISSUE THREAD

**Issue by Hypsellis** [An-Sar/PrimalCore#61] opened 2017-07-04 04:53 UTC
I get this crash randomly when I play, load or create a world https://pastebin.com/TehZ3aaN. I use PrimalCore 0.4.7 and Forge 13.20.1.2393.

**Comment by GeekyNinja** [comment] 2017-07-07 04:21
Also getting this on opening a world (preventing from opening it).

Gist below:
https://gist.github.com/GeekyNinja/4072bb24de4e0538c9cbccff858b7c3b

Minecraft 1.11.2
Forge 13.20.1.2393
Primal Core 0.4.8

**Comment by An-Sar** [comment] 2017-07-07 06:21
Thanks for the gist, as a short term fix you can set Features.PLANTS_AUTO_MAGIC to false in the config.

Unfortunately this bug seems to be difficult to reproduce, I can push you a dev build if you are willing to do some testing with your pack?

**Comment by GeekyNinja** [comment] 2017-07-08 11:44
Yes - happy to test for you @An-Sar 

It's happened one more time since I added the gist. I find it happens most in conjunction with Timberjack, Survivalist and Foragecraft, as it seems to be tree things (e.g. leaves) de-spawning that may make it happen? I did have it happen fairly often with Realistic Drops too, but even after disabling that it would still crash out.

Anything else I can do, let me know.

**Comment by An-Sar** [comment] 2017-07-09 02:08
I tried to reproduce with survivalist and rustic and so far no crash =/

**Comment by GeekyNinja** [comment] 2017-07-10 11:33
I always had problems with trees (and don't use rustic)... my combination is PrimalCore, Foragecraft, Quick Leaf Decay, Survivalist & Timberjack?

In saying that though, I've made the suggested change to PLANTS_AUTO_MAGIC and it's not happened again... just FYI.

**Comment by An-Sar** [comment] 2017-07-10 16:43
I'm glad the config option is working for you. I'm going to some more testing and will update you when I have a build to test. I appreciate the feedback.

**Comment by An-Sar** [comment] 2017-07-13 07:52
0.5.2 has a test fix for this crash, a dev build for the 1.11.2 branch is available upon request with the same fix.

**Comment by GeekyNinja** [comment] 2017-07-13 11:41
Happy to test if you need guinea pigs. I just won't be able to test for another 48 hours or so.

**Closed** 2017-10-28 09:34 UTC
Labels: bug, compatibility, Resolved
