### ISSUE TITLE
[1.12] Config isn't working

### ISSUE THREAD

**Issue by EmosewaGamer** [An-Sar/PrimalCore#62] opened 2017-07-06 12:03 UTC
I changed some config options for recipes and those recipes are still possible. I have not tested it with the bed.

**Comment by An-Sar** [comment] 2017-07-06 18:13
Looks like bed related configs are working, I need to do some further testing.

Were the options you tried related to removing vanilla recipes? because I know for sure recipe removal is not working currently.

**Comment by EmosewaGamer** [comment] 2017-07-07 12:20
Yup

**Comment by An-Sar** [comment] 2017-07-07 17:47
I have config options that disable my own recipes, I was specifically asking about vanilla recipes. There is a difference.

**Comment by An-Sar** [comment] 2017-07-10 21:28
The vanilla removal options should be sorted out and working for the next release, hopefully no more than a few days.

**Comment by An-Sar** [comment] 2017-07-13 07:51
A few of the removal configs still need attention, but the majority should be more or less working in 0.5.2

Feedback welcome

**Comment by Joxxs** [comment] 2017-07-14 10:15
Seems to have conflict with BetterWithMods specifically its Hardcore soil option.

With just Primal Core,BWM and JEI the recipe shows up for 4x soil piles = 1 dirt but can not craft.
With just BWM and JEI the recipes show up in JEI and work as intended.

Also the charcoal disable/gold tools is not working.

**Comment by An-Sar** [comment] 2017-07-14 18:48
Thanks for the info. The  gold tools config should be fixed for the next release. The remover for vanilla charcoal is going to take some reworking due to the new json recipes and the fact that it is a meta value of coal...

Also, I am working on the BWM conflict with primetoxinz, hopefully will be fixed in the next release as well, assuming it's on this end.

**Comment by An-Sar** [comment] 2017-07-14 19:40
Yeah this is a primal problem, working on it. I'm not entirely sure forge really supports removing vanilla recipes yet, so that feature might be disabled pending further development.

**Comment by An-Sar** [comment] 2017-07-14 20:15
False alarm, this should be fixed

**Closed** 2017-08-24 14:45 UTC
Labels: 1.12 and later, feedback wanted, Resolved
