### ISSUE TITLE
PrimalCore loaded a new chunk during chunk population causing cascading Worldgen lag

### ISSUE THREAD

**Issue by Rayzerfang** [An-Sar/PrimalCore#186] opened 2018-04-28 17:14 UTC
Playing Sevtech: Ages(v. 3.0.6) and I see this in my console continuously all the time.

**Comment by EEwing** [comment] 2018-05-11 02:33
For reference, this is a duplicate of #110

**Comment by kiwifrogg** [comment] 2018-05-11 02:45
The message is just a warning but in reality is not causing any issues, I have 2 primal core servers (one 7 months old) and neither have any issue related to this world gen message.

**Closed** 2018-05-31 16:57 UTC
Labels: World Gen, duplicate
