### ISSUE TITLE
Strange Nether Stone Recipe

### ISSUE THREAD

**Issue by Vyraal1** [An-Sar/PrimalCore#180] opened 2018-04-23 05:39 UTC
Seems like Nether Stone has a strange crafting recipe, 
![image](https://user-images.githubusercontent.com/26587049/39108514-9d33bcd8-4696-11e8-8468-bca0bb037e09.png)

which results in any combination of ingredients in a crafting table without a defined output to always make Nether Stone:
![image](https://user-images.githubusercontent.com/26587049/39108560-c7c68f8e-4696-11e8-8d9f-2e3e6304f06e.png)

and

![image](https://user-images.githubusercontent.com/26587049/39108578-e7bedfa8-4696-11e8-8c3d-c9fa49d3ba05.png)

It's an easy fix on the packside I guess by removing the Nether Stone recipe, but figured I might as well report it. I have not bothered reproducing in a PrimalCore + forge only environment.

**Comment by An-Sar** [comment] 2018-04-23 05:48
i cannot reproduce, do you have a mod list?

**Comment by Vyraal1** [comment] 2018-04-23 06:33
It's pretty large : https://hastebin.com/wehuyuxufi.nginx so I don't blame you if you want to close the issue right now haha, either way it's a pretty straight forward fix on my end, it might not even be primalcore's fault unless you have another idea.

**Comment by An-Sar** [comment] 2018-05-04 00:36
i believe this has been resolved in 0.6.50

**Closed by An-Sar** 2018-05-04 00:36 UTC
Labels: Resolved, compatibility
